In [5]:
import cv2
import numpy as np

path = "yoon.jpg"

img = cv2.imread(path) # 이미지를 ndarray로 저장했다
print(type(img))

<class 'numpy.ndarray'>


In [6]:
# 이미지를 와 크기를 출력

# 아래 3라인을 세트처럼 써야 작동 함
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

print(img.shape) # y, x, 채널 수 출력
print()

print(img.size) # y, x, 채널수를 곱한 값
print()

print(img.dtype) # img의 데이터타입
print()

(600, 900, 3)

1620000

uint8



In [8]:
# 이미지 색상 변경 후 출력하기

gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

cv2.imshow('Image', gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

print(gray.shape) # 채널수는 출력되지 않은 것 확인

(600, 900)


In [11]:
# 이미지 데이터의 픽셀값을 확인

print(img) # ndarray형태인 것 확인

[[[249 247 247]
  [250 248 248]
  [251 249 249]
  ...
  [249 247 247]
  [249 247 247]
  [249 247 247]]

 [[250 248 248]
  [250 248 248]
  [250 248 248]
  ...
  [249 247 247]
  [249 247 247]
  [249 247 247]]

 [[251 249 249]
  [251 249 249]
  [250 248 248]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 ...

 [[251 249 249]
  [251 249 249]
  [251 249 249]
  ...
  [249 249 249]
  [251 249 249]
  [250 248 248]]

 [[251 249 249]
  [251 249 249]
  [251 249 249]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[251 249 249]
  [251 249 249]
  [251 249 249]
  ...
  [248 248 248]
  [247 247 247]
  [248 248 248]]]


In [ ]:
# 이미지의 최소, 최대값 출력

print(img.min())

print(img.max())